dependencies:
  flutter:
    sdk: '^3.5.0'
  http: ^0.13.3           # Para realizar solicitudes HTTP a la API
  provider: ^6.0.2        # Para gestionar el estado (o riverpod: ^1.0.0 como alternativa)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4   # Para guías de estilo y limpieza de código